services:
  # Official Polygon.io MCP Server - Use external Docker image or build from GitHub
  polygon-io-server:
    # Option 1: Use official Docker image when available
    # image: ghcr.io/polygon-io/mcp-polygon:latest
    
    # Option 2: Build from external repository (recommended for updates)
    build: 
      context: https://github.com/polygon-io/mcp_polygon.git
    container_name: axiom-polygon-financial-mcp
    environment:
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - MCP_TRANSPORT=stdio
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - financial-mcp-network
    profiles:
      - "polygon"
    labels:
      - "axiom.service=external-financial-mcp"
      - "axiom.provider=polygon-io-official"
      - "axiom.type=real-time-market-data"
      - "axiom.cost=free-tier-premium-available"
      - "axiom.update-strategy=external-repo-build"

networks:
  financial-mcp-network:
    name: axiom-financial-mcp-external
    driver: bridge

# 🔄 EXTERNAL REFERENCE STRATEGY:
# 
# ✅ Benefits of this approach:
# 1. No embedded external repositories in our codebase
# 2. Always builds from latest upstream code
# 3. Automatic updates when we rebuild containers
# 4. Clean separation of Axiom code vs external dependencies
# 5. Easier maintenance and security updates
#
# 🚀 Usage Instructions:
#
# 📊 Start MCP servers with external builds:
#   docker-compose up --build -d
#
# 🔄 Update to latest versions:
#   docker-compose up --build --pull -d
#
# 💡 Alternative: Use MCP Settings Direct Installation
#   Configure MCP settings to use uvx/npm direct installation:
#   {
#     "polygon-io": {
#       "command": "uvx",
#       "args": ["--from", "git+https://github.com/polygon-io/mcp_polygon@latest", "mcp_polygon"],
#       "env": {"POLYGON_API_KEY": "your_key"}
#     }
#   }
#
# 🎯 Recommended Approach for Production:
# 1. For Polygon.io: Use uvx with git installation (as per official docs)
# 2. For Yahoo Finance: Use npm/pip direct installation from upstream
# 3. This docker-compose for development/testing only
#
# 📋 Environment Variables Required:
# - POLYGON_API_KEY: Get FREE key at https://polygon.io/
# - No keys needed for Yahoo Finance servers (100% FREE)