version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: axiom-streaming-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - axiom-streaming

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: axiom-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - axiom-streaming

volumes:
  redis-data:
    driver: local

networks:
  axiom-streaming:
    driver: bridge