# Prometheus Alert Rules for Derivatives Platform
# Critical: Sub-100 microsecond latency is non-negotiable

groups:
  # =============================================================================
  # CRITICAL PERFORMANCE ALERTS
  # =============================================================================
  - name: derivatives_performance_critical
    interval: 10s  # Evaluate every 10 seconds
    rules:
      # Latency SLA breach
      - alert: GreeksLatencyTooHigh
        expr: derivatives_greeks_latency_p95 > 100
        for: 1m
        labels:
          severity: critical
          component: greeks_engine
        annotations:
          summary: "Greeks calculation latency exceeded 100us"
          description: "P95 latency is {{ $value }}us (target: <100us). Client SLA at risk."
          action: "1. Check GPU utilization, 2. Scale up pods, 3. Review recent deployments"
      
      # Latency degradation
      - alert: GreeksLatencyDegrading
        expr: rate(derivatives_greeks_latency_sum[5m]) / rate(derivatives_greeks_latency_count[5m]) > 150
        for: 5m
        labels:
          severity: warning
          component: greeks_engine
        annotations:
          summary: "Greeks latency degrading over time"
          description: "Average latency trending upward: {{ $value }}us"
          action: "Investigate: memory leak, GPU throttling, or increased load"
      
      # Throughput too low
      - alert: GreeksThroughputLow
        expr: rate(derivatives_greeks_requests_total[1m]) < 1000
        for: 2m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "Low throughput detected"
          description: "Only {{ $value }} calculations/sec (target: 10,000+)"
          action: "Check: client traffic, system resources, or service degradation"

  # =============================================================================
  # ACCURACY ALERTS
  # =============================================================================
  - name: derivatives_accuracy
    interval: 60s
    rules:
      # Accuracy degradation
      - alert: GreeksAccuracyLow
        expr: derivatives_greeks_accuracy_vs_blackscholes < 0.999
        for: 5m
        labels:
          severity: critical
          component: greeks_engine
        annotations:
          summary: "Greeks accuracy below 99.9%"
          description: "Accuracy: {{ $value | humanizePercentage }}. Model may need retraining."
          action: "1. Compare with Black-Scholes, 2. Check model weights, 3. Review recent changes"

  # =============================================================================
  # SYSTEM HEALTH ALERTS
  # =============================================================================
  - name: derivatives_system_health
    interval: 30s
    rules:
      # API errors
      - alert: HighErrorRate
        expr: rate(derivatives_api_errors_total[5m]) > 0.01
        for: 2m
        labels:
          severity: critical
          component: api
        annotations:
          summary: "High API error rate"
          description: "Error rate: {{ $value | humanizePercentage }}"
          action: "Check logs, review recent deployments, verify dependencies"
      
      # GPU not available
      - alert: GPUNotAvailable
        expr: derivatives_gpu_available == 0
        for: 1m
        labels:
          severity: critical
          component: gpu
        annotations:
          summary: "GPU not available"
          description: "System running on CPU - latency will be 10x worse"
          action: "URGENT: Restart pod on GPU node or fix GPU drivers"
      
      # High GPU memory
      - alert: GPUMemoryHigh
        expr: derivatives_gpu_memory_used_percent > 90
        for: 5m
        labels:
          severity: warning
          component: gpu
        annotations:
          summary: "GPU memory usage high"
          description: "GPU memory: {{ $value }}%"
          action: "May need to reduce batch sizes or scale horizontally"

  # =============================================================================
  # DATABASE ALERTS
  # =============================================================================
  - name: derivatives_database
    interval: 60s
    rules:
      # PostgreSQL down
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "PostgreSQL is down"
          description: "Cannot store trades or positions"
          action: "URGENT: Restart PostgreSQL, check logs, verify disk space"
      
      # Redis down
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis cache is down"
          description: "Performance will degrade without caching"
          action: "Restart Redis, system will continue but slower"
      
      # Database connections high
      - alert: PostgreSQLConnectionsHigh
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "High number of database connections"
          description: "Active connections: {{ $value }} (max: 100)"
          action: "Check for connection leaks, consider connection pooling"

  # =============================================================================
  # BUSINESS METRICS ALERTS
  # =============================================================================
  - name: derivatives_business
    interval: 60s
    rules:
      # Trading stopped
      - alert: NoTradesExecuted
        expr: increase(derivatives_trades_total[10m]) == 0
        for: 10m
        labels:
          severity: warning
          component: trading
        annotations:
          summary: "No trades executed in 10 minutes"
          description: "Trading may have stopped or very low activity"
          action: "Check: market hours, client connectivity, system issues"
      
      # Large loss
      - alert: LargeDailyLoss
        expr: derivatives_daily_pnl_usd < -100000
        for: 1m
        labels:
          severity: critical
          component: risk
        annotations:
          summary: "Large daily loss detected"
          description: "Daily P&L: ${{ $value }}"
          action: "URGENT: Review positions, check for model errors, contact client"
      
      # Greeks limits breached
      - alert: DeltaLimitBreached
        expr: abs(derivatives_portfolio_delta) > 10000
        for: 5m
        labels:
          severity: warning
          component: risk
        annotations:
          summary: "Portfolio delta exceeds limits"
          description: "Total delta: {{ $value }}"
          action: "Auto-hedger should trigger, verify it's working"

# =============================================================================
# NOTIFICATION ROUTING
# =============================================================================

# Severity levels:
# - critical: Page on-call engineer immediately
# - warning: Slack notification
# - info: Email only

# Response times:
# - critical: <15 minutes
# - warning: <1 hour
# - info: <24 hours